version: "3"

services:
  strapi:
    image: node:16
    working_dir: /usr/app
    user: node
    ports:
      - 1337:1337
    command: yarn develop
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_DATABASE: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: my-secret-pw
    volumes:
      - ./backend:/usr/app
    depends_on:
      - db

  blog:
    image: node:16
    working_dir: /usr/app
    user: node
    expose:
      - 3000
    ports:
      - 3000:3000
    command: npm start
    environment:
      REACT_APP_BACKEND_URL: http://localhost:1337
    volumes:
      - ./frontend:/usr/app
    depends_on:
      - strapi

  db:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: my-secret-pw
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
