# fly.toml file generated for strapi-campderrich on 2022-10-14T12:59:47+02:00

app = "strapi-campderrich"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  AWS_BUCKET = "sergio-g-campderrich-strapi-bucket"
  AWS_REGION = "eu-west-1"
  NODE_ENV = "production"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 1337
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
