name: Docker

on:
  push:
    branches: [ "master" ]
    paths: [ "backend/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into Docker Hub registry
        uses: docker/login-action@v1
        with:
          username: gio8tisu
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log into Heroku registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: gio8.tisu+heroku@gmail.com
          password: ${{ secrets.HEROKU_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            gio8tisu/strapi-blog
            registry.heroku.com/strapi-campderrich/web

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
